### ISSUE TITLE
Add to documentation that the names of shared themes directories may not be the repo slug

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/hammer#21]
When using shared partials locally, your cloned directories may be different from that on the production environment.

Example:

Local

```
/cleanslate_themes/
|_my-awesome-theme
|_shared-theme
```

Server

```
/themes_dir/
|_my-awesome-theme
|_shared
```

Using: `<r:partial name="patterns/wvu-masthead" theme="shared-theme" />` locally would work fine, however if you push this code live the partial will not load.

This issue is due to the fact you can name the theme with in CleanSlate when it is deployed.  For Hammer this is analogous to the clone process `git clone {repo} {directory}`.

Hammer assumes the name of the repo by its container directory.

Reference wvuweb/cleanslate-cms#145

**Comment by nreckart** [comment]
wvuweb/cleanslate-cms#124 is related to making themes accessible by Stash slug. Just noting that here.

**Comment by zeroedin** [comment]
Reference #22

**Comment by zeroedin** [comment]
I don't believe this is an issue any more.  closing
