### ISSUE TITLE
Partials break unless paths are relative to current file

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/hammer#25]
Partial Not Found: /srv/cleanslate_themes/prof-tech-demo-site/views/layouts/patterns/_wvu-masthead--mini.html

patterns/ should work (it does in CleanSlate), but when partials contain references to other partials within the same patterns/ folder, the partial breaks in hammer. Hopefully that makes sense.

**Comment by zeroedin** [comment]
Fixed in @d78a471cd6ed111dfc7e17e6e2eb015b22fac781
