### ISSUE TITLE
Hammer VM - Consol Error

### ISSUE THREAD

**Issue by dustinmazon** [wvuweb/hammer#35]
Ran into this error in the consol when running hammer-vm

Uncaught SyntaxError: Unexpected token

![screen shot 2015-07-29 at 12 44 32 pm](https://cloud.githubusercontent.com/assets/1126703/8963764/cc7c046a-35ef-11e5-85a9-94210a7d7793.png)

**Comment by zeroedin** [comment]
Wrong repo.

**Comment by zeroedin** [comment]
AJ telling me wrong things.  I blame him.

**Comment by zeroedin** [comment]
@reference #19
