### ISSUE TITLE
Add support for attributes to r:files

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer#36]
It'd be sweet if hammer would support the attributes for `r:files` like `labels`, `limit`, `types`, and `random`. I'd wager the most noticeable ones are `limit` and maybe `random`. Code snippet:

``` html
<style>
.example {
  background-image: url(<r:files:each labels="random-image-collection" limit="1" types="image" random="true"><r:file:image_url size="1560x636" /></r:files:each>);
}
</style>
```

Having a look through `cleanslate/lib/slate/radius/tags/asset.rb` will likely be helpful. 

Related to #19.

**Comment by zeroedin** [comment]
@adamjohnson when you can test out what functionality here is still missing and what needs added.

**Comment by zeroedin** [comment]
Marking as fixed in https://github.com/wvuweb/hammer/commit/849a79a5ea10c1db8996664db6643b3f8fe5217c
