### ISSUE TITLE
Shared themes with different name vs repo names are busted

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer#41]
## Steps to reproduce the issue

  1. Clone the [Adventure WV Repo](https://stash.development.wvu.edu/projects/CST/repos/student-life-adventure-wv/browse) and the [Adventure WV Orientation repo](https://stash.development.wvu.edu/projects/CST/repos/student-life-adventure-wv-orientation/browse) from Stash.
  1. Create a partial named `_hello-world.html` in `cleanslate_themes/student-life-adventure-wv/views/shared`.
  1. Add an `<h1>` inside the file with `Hello World` as it's content.
  1. Start hammer.
  1. Open the Adventure WV Orientation theme in your text editor.
  1. Open `frontpage.html`. Paste `<r:partial name="shared/hello-world" theme="Student Life: Adventure WV" />`.
  1. Open the Mock Data file and add this under the shared themes key: 

```yaml
  "Student Life: Adventure WV":
    "shared/hello-world": "student-life-adventure-wv"
```

View [http://localhost:2000/student-life-adventure-wv-orientation/views/frontpage.html](http://localhost:2000/student-life-adventure-wv-orientation/views/frontpage.html) in your browser.

## Results

Hammer cannot find the shared partial and throws an error.

## Expected results

Hammer should find the shared partial and print its contents.

I suspect this error stems from having fancy characters in the theme name. Eg: `Student Life: Adventure WV`.

**Comment by adamjohnson** [comment]
#22 is related to this.

**Comment by zeroedin** [comment]
Link in commit message didn't work correctly should link to: https://github.com/wvuweb/hammer/commit/d78a471cd6ed111dfc7e17e6e2eb015b22fac781
