### ISSUE TITLE
Add support for   <r:stylesheet_content />

### ISSUE THREAD

**Issue by jasonmarkle** [wvuweb/hammer#52]
If possible could you add in support for the new <r:inlines_stylesheet/> tag @zeroedin ? It would be much appreciated.

**Comment by nreckart** [comment]
There is no `<r:inline_stylesheet>` tag. It is `<r:stylesheet_content>`, which states what the tag is doing more clearly. All it's doing is returning the content of the stylesheet file.

**Comment by jasonmarkle** [comment]
@nreckart Sorry about that, juggling to many things and missed the naming convention. Thanks for the correction.

**Comment by zeroedin** [comment]
This was added in wvuweb/hammer@a0646ad6e4cec7a70c47954cd828a4214ad2fe09
