### ISSUE TITLE
Allow users to configure the URL for "Home" in breadcrumbs

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer#55]
![Link text used for multiple different destinations error](https://user-images.githubusercontent.com/575865/51210453-d19d5200-18e0-11e9-9b9a-85700ef11943.png)

We see this accessibility error in local development on every single site we make. The "Home" `href` in the main nav is different from the "Home" `href` in the breadcrumbs. For example, one is:

  * `https://launchlab.wvu.edu/home`
  * and the other is:
  * `#home`

I would like to be able to customize the content of the `href` attribute in the `r:breadcrumbs` tag. I think this will help CleanSlate designers when remediating their sites. People like to be able to achieve a "clean slate" in local development (_see what I did there?_). 

Relevant: 

https://github.com/wvuweb/hammer/blob/master/hammer/services/tags/basic.rb#L487

**Comment by zeroedin** [comment]
I believe you can already do this by adding a `breadcrumbs` data point in mock_data.yml

```yaml
breadcrumbs: |
  <ul class="whatever">
    <li><a href="/">Home</a></li>
    <li class="active">Page</li>
  </ul>
```
By doing this however you lose the interpolation of attribute options from the radius tag.
