### ISSUE TITLE
Blog index pages are unable to display blog article content

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer#57]
After the recent merge test > dev > master (#56), blog index pages are unable to display each articles' content via `<r:article:content name="article-body" />`.

You can see and test this behavior by using the UR Social theme:

https://bitbucket.org/wvudigital/ur-social/src/master/

Their blog uses the `news.html` and `news-item.html` templates:

https://bitbucket.org/wvudigital/ur-social/src/master/views/news.html

https://bitbucket.org/wvudigital/ur-social/src/master/views/news-item.html

**Comment by zeroedin** [comment]
@adamjohnson  reference commit d4298c9720d344e4a69b9a93ca8b0b1e379e76ac  give dev branch a pull and give it try.

**Comment by adamjohnson** [comment]
Playing with this for a few hours, initial results seem good. I'll keep testing and report back.

**Comment by adamjohnson** [comment]
Looks good. 👍
