### ISSUE TITLE
Give a more helpful error message when the blog array in mock data isn't formatted properly

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer#59]
## Steps to reproduce the issue:

1. Clone the [graduate-admissions](https://bitbucket.org/wvudigital/graduate-admissions/src/master/) theme.
2. Go to the [`blog_article.html`](http://localhost:2000/graduate-admissions/views/blog_article.html) or [`blog_index.html`](http://localhost:2000/graduate-admissions/views/blog_index.html) templates via hammer.

## Results

Hammer outputs:

```
no implicit conversion of String into Integer
```

## Expected Results

Is it possible to output a more helpful error message here? For example:

> The `blog` key in your mock_data file is improperly formatted. See [Hammer on Github](https://github.com/wvuweb/hammer) for an example of a properly formatted `blog` key.

**Comment by zeroedin** [comment]
This was fixed but not closed in https://github.com/wvuweb/hammer/commit/f0a5d49017937a24d16d6e413378733c1a6e183a
