### ISSUE TITLE
Windows and pik updates for readme 

### ISSUE THREAD

**Issue by architarious** [wvuweb/hammer#8]
Need to make sure Ruby v1.9.3 is installed along with it's devkit. 
Users may need to reinstall Ruby v2.0.0 / v2.1.3 depending whether they're already using anything else on their system that requires versions newer than 1.9.3.

Here was my process that got things to work:

Install ruby 1.9.3
Install ruby devkit for 1.9.3
gem install pik
mkdir c:\bin
cd c:\bin
pik_install c:\bin (or whatever dir u want)
add c:\bin; to the windows path via system properties -> advanced -> environment variables
pik add C:\ruby193\bin  (or wherever ruby193 is installed on your machine)
pik sw 193

After this, the normal hammer install instructions work and the bundle will install, else there are lots of issues with devkits, json, nokogiri, and a handful of other gems.

If you're running a newer version of ruby by default (you installed 2.0.0/2.1.3 after 1.9.3), you'll need to run "pik sw 193" each time you start up your command prompt and before you run hammer.bat

Also, pik doesn't run in the GIT BASH, you have to use the windows command prompt. However,  there's steps and a description here for how to get it working with GIT: http://rubyonwindowsguides.github.io/book/ch02-03.html     ,.. but I wasn't able to get it to work and gave up early.

Alternatively, it's worth noting that the ruby193 installer loads it's own special command prompt that only runs ruby193 (even if you've got 213 installed and set as default) and it's accessible in the start menu where all the other ruby193 stuff is. So potentially, if you install ruby193, you don't even have to use pik, you could just open that prompt up every time instead and only use it for hammer. That's something that I wish I would have realized earlier.

**Comment by zeroedin** [comment]
This issue is a moot point with the creation of Hammer in a VM: [Hammer-VM](https://github.com/wvuweb/hammer-vm)
