### ISSUE TITLE
Calling a missing yaml partial causes white screen of death without a helpful error message.

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer#81]
## Steps to reproduce:

  1. Clone housing
  1. Start hammer and go to any template.
  1. Open your mock data file and try to include a yaml partial like so: `<%= YAML::include("does-not-exist.yml") %>`

## Results:

```
Internal Server Error
(<unknown>): could not find expected ':' while scanning a simple key at line 23 column 1
WEBrick/1.4.2 (Ruby/2.3.1/2016-04-26) at localhost:2000
```

## Expected Results

Hammer should render a helpful error so the user can troubleshoot and fix the issue. Ideally this doesn't cause a white screen of death.

**Comment by zeroedin** [comment]
Fixed in https://github.com/wvuweb/hammer/commit/222feb98f6371d144183e77d3158acb43f5ca507
